# Generated by Django 3.2 on 2023-03-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'USER'), ('admin', 'ADMIN'), ('moderator', 'MODERATOR')], default='user', max_length=15, verbose_name='role'),
        ),
    ]
